apiVersion: manifests/v1beta1
metadata:
  name: uan
spec:
  charts:
  - name: cray-uan-install
    version: 1.1.42
    namespace: services
    values:
      cray-import-config:
        catalog:
          image:
            tag: 0.4.2
        config_image:
          name: cray-uan-config
          tag: 0.2.37
        import_job:
          CF_IMPORT_PRODUCT_VERSION: "@product_version@"
      cray-import-kiwi-recipe-image:
        catalog:
          image:
            tag: 0.4.2
        import_image:
          name: cray-uan-image-recipe
          tag: 0.2.37
        import_job:
          name: "uan-image-recipe-import-@product_version@"
          PRODUCT_VERSION: "@product_version@"
